import type { Metadata } from "next";
import Script from "next/script";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  other: {
    ["urn:adobe:aue:config:service"]: "https://localhost:8000",
    ["urn:adobe:aue:system:aemconnection"]: "aem:https://localhost:8443",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <Script
          src="https://localhost:8000/corslib/LATEST"
          strategy="beforeInteractive"
        />
      </head>
      <body>{children}</body>
    </html>
  );
}
